# Generated by Django 5.0.6 on 2024-06-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='место')),
                ('time', models.TimeField(verbose_name='время')),
                ('action', models.CharField(max_length=300, verbose_name='действие')),
                ('is_pleasant', models.BooleanField(verbose_name='признак приятной привычки')),
                ('periodicity', models.IntegerField(default=1, verbose_name='периодичность')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='вознаграждение')),
                ('time_to_complete', models.CharField(verbose_name='время на выполнение в секундах')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
