# Generated by Django 5.0.6 on 2024-06-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.IntegerField(verbose_name='время на выполнение в секундах'),
        ),
    ]
